### ISSUE TITLE
RDF Transform extension not showing on OpenRefine GUI

### ISSUE THREAD

**Issue by luizbonino** [AtesComp/rdf-transform#10]
I installed the RDF Transform according to your instructions on my Mac where I already had a working OpenRefine (v. 3.5.2) but it doesn't show at the OpenRefine GUI. I stopped the OpenRefine service, installed the RDF Transform extension and started OpenRefine again with no success. 
I tried tried to install on both the ~/Library/Application Support/OpenRefine/extensions/rdf-transform and on the OpenRefine package (Contents/Resources/webapp/extensions/rdf-transform), also with no success. Is there anything else I should do to make it work?

**Comment by AtesComp** [comment]
Check the version of Java you have installed.  RDF Transform requires Java 11 to Java 17.  Most installs for OpenRefine use the older Java 8.

**Comment by AtesComp** [comment]
See the install [Prerequisites](https://github.com/AtesComp/rdf-transform/wiki/Install#prerequisites) for more on the issue.

**Comment by AtesComp** [comment]
I'm assuming this solved the issue.

**Comment by luizbonino** [comment]
Not really. I'm using JDK 17.0.1 and OpenRefine 3.5.2

**Comment by AtesComp** [comment]
Make sure OpenRefine is running with Java 17.  OpenRefine will use the system default.  If Java 8 and Java 17 are installed or OpenRefine is bundled with the JRE, it may still be running Java 8.  See the "refine" script file if you are using it.  Also, check and set your Java environment variables for the proper version.

Alternatively, make sure Java 8 is uninstalled if you don't need it for other projects.  Java 17 should run Java 8 code ok.

**Comment by AtesComp** [comment]
NOTE: The Mac kit currently includes Java by default.  It is documented [here](https://openrefine.org/download.html) and elsewhere.  The bundled Java should be removed or redirected to a later version with the JAVA_HOME env variable.

**Comment by AtesComp** [comment]
Please update as this issues is almost assured to be a Java version issue.  Try OpenRefine-beta2 as it bundles Java 11.
