### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by zgramana** [AtesComp/rdf-transform#15]
Looking at `LICENSE.txt` it appears to be reporting on the licenses of dependencies only, but not your code under the `src` tree. Since there are no license headers, it is unclear whether your code is also licensed under Apache 2.0 or is unlicensed.

If you intend your software to be permissively licensed, do you mind clarifying `LICENSE.txt` with your desired license (preferably Apache 2.0) and/or adding license headers to your source files?

Much appreciated!

**Comment by AtesComp** [comment]
Thanks.  This was an oversight and holdover from the related originating project, [grefine-rdf-extension](https://github.com/stkenny/grefine-rdf-extension).

Please review the updated LICENSE.txt file to verify it clarifies the issue.

**Comment by AtesComp** [comment]
Updated all files to include licensing text in [bc8a191](https://github.com/AtesComp/rdf-transform/commit/bc8a191252b3f92c14f24440139f3edc60a03d35).

**Comment by zgramana** [comment]
@AtesComp much appreciated, thanks!

**Comment by tfmorris** [comment]
But, if this is based on the original DERI code (which doesn't seem to be credited anywhere), you can't invent a license for it yourself. I don't know Irish/EU copyright law well, but I suspect the original code is copyright by Fadi Malli even though it doesn't include a copyright statement.

Is there a reason that this wasn't started as a fork of the original repo? That makes the provenance hard to follow.
