### ISSUE TITLE
Download link for the rdf-transform-2.2.1 is not correct

### ISSUE THREAD

**Issue by kits-ragh** [AtesComp/rdf-transform#19]
Hi, 

I was downloading latest version of rdf-transform-2.2.1 but got "Not Found" error message on screen. 

Checked the download url: 
https://github.com/AtesComp/rdf-transform/releases/download/v2.2.0/rdf-transform-2.2.1.zip

Version is not correctly mapped. 

The correct url is : 
https://github.com/AtesComp/rdf-transform/releases/download/v2.2.1/rdf-transform-2.2.1.zip

**Comment by AtesComp** [comment]
Thanks.  I'll fix shortly.

**Comment by AtesComp** [comment]
The release was incorrectly linked in the readme. All other release links work correctly.

Fixed on commit 8143761
