### ISSUE TITLE
Maintaining this repository in the OpenRefine github organization?

### ISSUE THREAD

**Issue by wetneb** [AtesComp/rdf-transform#7]
Hi @AtesComp,

Again, thank you so much for working on this! This new RDF extension looks really great.
Before you published it, we were in talks with the current maintainer of the older RDF extension to transfer it to OpenRefine's GitHub organization, as a means to give it more visibility (this has not progressed because the maintainer has not responded to this invitation yet).

If that is interest to you, we could do this for your extension instead. We would of course give you all admin rights on the repository.

I still have in mind your request for more documentation about the migration process for OpenRefine 4.0 - I hope to find the time to work on this soon.

If there is anything else we can do to support your work, let us know :)

**Comment by AtesComp** [comment]
I'm up for joining the OR GitHub.

The migration docs would be good but I know it's in the early stages.

I struggled a bit...well, a lot...with the OpenRefine extension  programming as there were a few extension design issues that closely relied on OR's code.  As documentation was a bit lacking, I resorted to examining OR code directly.  You can see some of this in the controller.js file's comments.  Butterfly's documentation is also very poor and it's JS engine implementation is very simplistic.  I'm hoping the 4.0 version will enhance that.  Also, Butterfly documents that the controller could be Java based and pointed to by the module configuration.  How would we do that in OR as that could easily overcome the JS server side limitations?

I've contemplated rewriting the extension coding PDF as it missed several issues I dealt with and the ordering of the documentation doesn't flow with the direction of programming effort...things you need to know upfront are not addressed until later.

**Comment by wetneb** [comment]
>  Also, Butterfly documents that the controller could be Java based and pointed to by the module configuration.

I had no idea! That would make a lot more sense than this weird Javascript.

Concerning documentation of the current architecture, I am always torn between:
* the urge to document the status quo
* the urge to migrate out of Butterfly instead

meaning that none of the two happen :-D
